### ISSUE TITLE
Standardize function arguments

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#132]
I noticed that we use different argument names between functions for the same thing. For instance, change_tv uses ```dat_file_out``` while change_lcomp uses ```outfile```. We should try to standardize those.

Edit 2015-06-22 by Sean. A list to check:

- [x] change_data.r
- [x] change_e.r
- [x] change_em_binning.r
- [x] change_f.r
- [x] change_fltname.r
- [x] change_lcomp_constant.R
- [x] change_maturity.R
- [x] change_rec_devs.r
- [x] change_retro.r
- [x] change_tail_compression.R
- [x] change_tv.r
- [x] change_year.R
- [x] clean_data.r
- [x] sample_agecomp.R
- [x] sample_calcomp.R
- [x] sample_index.r
- [x] sample_lcomp.R
- [x] sample_mlacomp.R
- [x] sample_wtatage.R
- [x] standardize_bounds.R
- [x] verify_input.r

**Comment by kellijohnson** [comment]
Can we agree on standard names for the in and out files? I am trying to work through some documentation.

**Comment by seananderson** [comment]
Thanks for taking that on, Kelli.

I think I like what you did with `change_tv`: `starter_file_in`, `dat_file_out`, `ctl_file_in` etc. Even in cases where there's only one type of file going in or out. That makes it explicit about what type of file it is, that it's a filename argument, and whether it's input or output. I could see maybe omitting the `file` part of the argument name, but I like that when `file` is part of the name it's obvious that it's not a case argument to specify.

We'll have to make sure the the corresponding arguments get changed in `ss3sim_base` as well as throughout any other functions that may call the function by searching for that function call across all `.R`. files.

**Comment by kellijohnson** [comment]
I think having ```_file_``` is imperative if we are going to keep things 
like ```datfile``` for ```datfile <- SS_readdat(dat_file_in)```. Should 
we have a table or checklist for each function so we can keep track of 
which functions have been checked?

**Comment by seananderson** [comment]
I had a quick scan through the functions and added a list of functions to check to the top post in this thread. I think(?) that you or any member of this group should be able to click on those check boxes or edit the post.

The other question is what to call the list object that represents the SS data file as read by r4ss. I'm OK with leaving that as `datfile`, but I'm open to suggestions. We could also call that `dat_list` or something like that.

**Comment by kellijohnson** [comment]
Yep it looks like I can edit it, thanks.
For the clarity of the package I like `dat_list`, `dat_in`, and `dat_out`. Work wise I do not like it so much. I think its a good  move though and will alleviate pains later. I think we should do it even if there is only one object.

**Comment by kellijohnson** [comment]
With 
* `dat`
* `par`
* `ctl`
* `str`
* `for`

**Comment by colemonnahan** [comment]
I can't help with this until I'm back, but one thought is to adopt the naming style from `r4ss`...

**Comment by taylori** [comment]
If only there were anything worthy of a "naming style" in r4ss.
Sadly there are all kinds of inconsistencies in names among functions,
within functions, and relative to SS itself. If anything, I'm happy to
discuss standardization of names at some point in the future, but I'm not
sure it's a good model at the moment.
-Ian

**Comment by kellijohnson** [comment]
I think where possible using r4ss naming is great, but I think we should also use some standardization not in r4ss, such as '_in' and '_out' and naming arguments specifically even if there is only one file being read in and out. This will alleviate having to change things if later another file is added. It would be great if people could comment on the following so we can move forward:
* Reading in a file (`_in')
* Writing a file ('_out')
* r4ss list ('_list') (e.g., `rep_list', 'for_list')
* report == rep, forecast == for, starter == ?, data == dat

**Comment by kellijohnson** [comment]
Or r4ss uses:
* Reading in a file ('ctlfile`)
* Writing a file (`newctlfile`)

**Comment by seananderson** [comment]
@kellijohnson , so are you proposing, for example, `str_in`, `dat_in`, `dat_out`, and `dat_list`, and dropping the `file` in the middle of the file argument names? I could go either way on including or excluding `file`.

**Comment by kellijohnson** [comment]
Yes I was just for brevity, but I am also on the fence b/c if we keep `file` then we will have less to change. Or if people want to switch to more of an r4ss we could use `ctlfile` instead of `ctl_file_in`

**Comment by seananderson** [comment]
Why don't we start with leaving `file` in the middle of each file argument name. That will minimize the code to change initially — especially for the larger `change_e` and `change_tv` functions. It would be really easy to do a global search and replace and remove `_file` after once things are standardized.

I kind of like the underscore approach because it matches the argument and function naming style through the rest of the package.

Looks like there are 21 files to check at the top. If you (@kelliwant to take on the top 10, I'll do the bottom 11.

**Comment by kellijohnson** [comment]
got it, i will probably start tomorrow.

**Comment by seananderson** [comment]
OK, I started standardizing the input, output and data list object argument names in this branch: https://github.com/ss3sim/ss3sim/tree/standardize-arguments

I switched `datfile` to `dat_list` across all the functions since it was easier to just do them all at once.

`R CMD check` seems happy and the unit tests run.

Some notes:
- I forget how `change_tv` is working, but the file name arguments don't get specified in `ss3sim_base`. I assume this is fine since the default argument file names work.
- don't forget to check the unit tests in `tests/testthat`
- the unit tests run, but I don't think they test the data manipulation functions very thoroughly so it's possible I missed something
- I left `outfile` throughout the sample functions. This argument is used for both data files and weight at age files through the template `lcomp-agecomp-index.R`. I'm not sure it's worth the added complexity of splitting that up.
- using `grep` is a quick way to make sure you didn't miss anything. E.g. `grep -R "datfile" .`
- I used `rpt_file_in` etc. for the report files

**Comment by kellijohnson** [comment]
made some headway with a few things noted above.

**Comment by kellijohnson** [comment]
other than `outfile` I think we are good to go

**Comment by kellijohnson** [comment]
@seananderson can we merge the branches and close this issue?

**Comment by seananderson** [comment]
Merged into master now. Thanks for the added clean up of `change_e`. That's also merged.
