### ISSUE TITLE
change_e datfile

### ISSUE THREAD

**Issue by kellijohnson** [ss3sim/ss3sim#196]
Should the ```dat_file_in = ss3.dat``` read in by ```change_e``` be changed to use ```dat_file_in = datfile```, as the list is already in the environment and this would eliminate another instance of the datfile being read in? I think nothing changes the contents of the ```datfile``` between line 449 and 469 of ```ss3sim_base```.

**Comment by seananderson** [comment]
In theory this would be ideal. Problem is that `change_e` is coded to read in the `.dat` file multiple times itself. Some could be quickly replaced but others use `readLines`. I don't have a feeling for how much time is lost by reading in the data file given realistic volumes of data we may have. If it's not much time lost then I'd vote for just moving on at this point. Otherwise `change_e` could be edited to work with the r4ss list format of data.

**Comment by kellijohnson** [comment]
```datfile``` is only used to get the end year, which is easily obtained from the list. I am fine with taking 10 minutes to change it, if you think its something we should do. Or I can just move on.

**Comment by colemonnahan** [comment]
Reading the datfile typically is a negligible amount of time. However, for consistency and clarity I vote to update `change_e` to use the already-read-in datfile. Although it might be better to do all of that at once at some point, including cleaning up argument names. Sometimes it's `infile` sometimes it's `datfile`, for example. (Should we make a new issue just for this??)

Low priority in the next few weeks but I marked it CRAN to remember to do it at some point.

**Comment by taylori** [comment]
I'm happy to add any of you as contributors to r4ss on GitHub (Sean already
is) if the ability to modify the SS_readdat would in any way make it easier
to make this change in ss3sim.
-Ian

**Comment by kellijohnson** [comment]
The naming convention issue is already listed in #132. Which I have also now marked for CRAN. Maybe we can use #132 to discuss ideas for best practices.

**Comment by kellijohnson** [comment]
This was fixed with 2215c5ce3286d1403457a4c5cbf8c1f8326150a8 along with #132 which is also now closed.
