### ISSUE TITLE
Add function that checks validity of .dat file

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#203]
We have some checks for conformity throughout our code that checks for a valid .dat file. For instance it must be one gender. I propose we incorporate these checks into the [`is_ssdat_file`] (https://github.com/ss3sim/ss3sim/blob/9ed4a1d8373b2d66928c8489bc168cb669312509/R/change_data.r#L296) function, and rename it so something like `verify_datfile` which has informative errors and warnings. This would be called for basically any function manipulating the datfile. I think this would help clean up the error checking and make it easier moving forward.

**Comment by seananderson** [comment]
That sounds like a great idea. If we compile a list of things we want to check for, I'm happy to carry this out.

I can think of:

```R
datfile$Ngenders == 1
datfile$lbin_method <= 2
datfile$Lbin_method == 2
```

What else?

**Comment by colemonnahan** [comment]
@Kotkot will have some good ideas. Of the top of my head: 

* Checking for the right fleet structure
* Dummy index data covering all years (we currently don't do this with `change_data` although probably should)

**Comment by Kotkot** [comment]
Things that I can think of for this simulation study:

1 #_Nfleet
2 #_Nsurveys
1 #_N_areas
Fishery%Survey%CPUE
0.5 0.5 0.5 #_surveytiming_in_season
1 1 1 #_area_assignments_for_each_fishery_and_survey

100 #_N_lines_of_catch_to_read

0 #_N_fleets_with_discard
0 #N discard obs
0 #_N_meanbodywt_obs

Ageing error definition (i.e: -1 for ages and 0.001 for the actual value)
e.g
-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1
0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001	0.001

There may be more...

**Comment by colemonnahan** [comment]
We'll certainly find more. The nice thing about this function is we can add them in one central place (or remove them if we later expand functionality of the package).

**Comment by seananderson** [comment]
I've created `check_data` that performs the checks listed above. I added it to the master branch, but I haven't yet removed `is_ssdat_file` or integrated the check throughout the manipulation functions. See this commit: https://github.com/ss3sim/ss3sim/commit/63664cbf9caddfec628cdb146048af7bd099bd78

A number of our current models over in ss3models will fail these checks so I can't integrate this just yet. For example, the dummy index data starts at year 26 in many of the models and `Lbin_method` is sometimes set to 1.

I added [a unit test](https://github.com/ss3sim/ss3models/blob/package/tests/testthat/test-models.R) to the unmerged ss3models package that will run all the .dat files through this function.

**Comment by seananderson** [comment]
I merged this into master and switched all previous `is_ssdat_file` calls for `check_data`:
https://github.com/ss3sim/ss3sim/commit/7b9dd270cbd0760724ea0bb306fd0cf8106da23d

To do this I commented out all the checks that would fail on the current model setups over in ss3models:
https://github.com/ss3sim/ss3sim/commit/7b9dd270cbd0760724ea0bb306fd0cf8106da23d

These are things we should clean up in the other repository and then we can re-enable all the checks. I'm not sure we want to check the 100 years thing. Seems like it's an unnecessary restriction. I can start cleaning up those issues as long as someone else isn't deeply into modifying these models currently. Would also be easier to make those changes in the package formatted repo, since that's how all the unit tests run to check this. So, perhaps I'll wait until I get the go ahead to merge that `package` branch of ss3models into master.
