### ISSUE TITLE
user_recdevs and parallel w/ bias_adjust

### ISSUE THREAD

**Issue by kellijohnson** [ss3sim/ss3sim#207]
@seananderson somewhere you referenced the fact that bias adjustment does not work in parallel or with parallel iterations? I am having problems when I have ```parallel = TRUE``` and ```parallel_iterations = TRUE``` while ```bias_adjust = TRUE``` in that it will do the bias adjustment, calculate the values and place them in the ctl file within the bias folder but then when it does the iterations it goes back to the old file. Not sure what is going on. I tried using ```browser()``` to follow it through but couldn't find the problem. Also in the log file it says bias adjustment is FALSE even though a bias folder exists.
```r
library(devtools)
load_all("c:/ss/ss3sim")
load_all("c:/ss/ss3models")
(om <- system.file("models/cod/om", package = "ss3models"))
(em <- system.file("models/cod/em", package = "ss3models"))
case_folder <- system.file("cases", package = "ss3models")
Eps <- matrix(rnorm(100*20, 0, 0.02), nrow = 100, ncol = 20)
run_ss3sim(iterations = 1:3, scenarios = "L30-F0-E0-I0-cod", 
  case_files = list(L="lcomp", F="F",I="index", E = "E"),
  case_folder = case_folder, om_dir = om, em_dir = em, 
  bias_adjust = TRUE, bias_nsim = 1, user_recdevs = Eps, 
  show.output.on.console = FALSE, parallel = TRUE, parallel_iterations = TRUE)
```
I do not have the problem if I take the user recruitment deviations away.

**Comment by seananderson** [comment]
Found the bug. Sorry about that. When I was fixing a bug in how the parallel iteration code passed the `...` arguments for Cole I accidentally set `bias_already_run = FALSE` when previously it was `= TRUE`. Nothing to do with the user recdevs. Looks like it was broken no matter what.

For parallel iterations, the bias runs are run sequentially first. Then the `bias_adjust` argument is set to `FALSE` (which is why it would say that in the log file, maybe we should fix that), `bias_already_run` is set to `TRUE`, and the regular iterations are run in parallel. `bias_already_run = TRUE` tells `ss3sim_base` to look in a previously created `bias` folder.

Parallel iterations have been the source of more mistakes and frustration than anything else in the wrapper function, but I guess they're pretty useful to have.

Note how you can also use the `bias_already_run = TRUE` option to force the use of previously run bias runs yourself.

**Comment by kellijohnson** [comment]
Great, everything seems to be working now.

On Sun, Feb 22, 2015 at 6:36 AM, Sean Anderson <notifications@github.com>
wrote:

> Found the bug. Sorry about that. When I was fixing a bug in how the
> parallel iteration code passed the ... arguments for Cole I accidentally
> set bias_already_run = FALSE when previously it was = TRUE. Nothing to do
> with the user recdevs. Looks like it was broken no matter what.
>
> For parallel iterations, the bias runs are run sequentially first. Then
> the bias_adjust argument is set to FALSE (which is why it would say that
> in the log file, maybe we should fix that), bias_already_run is set to
> TRUE, and the regular iterations are run in parallel. bias_already_run =
> TRUE tells ss3sim_base to look in a previously created bias folder.
>
> Parallel iterations have been the source of more mistakes and frustration
> than anything else in the wrapper function, but I guess they're pretty
> useful to have.
>
> Note how you can also use the bias_already_run = TRUE option to force the
> use of previously run bias runs yourself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/issues/207#issuecomment-75438164>.
>



-- 
Kelli Faye Johnson
kellifayejohnson@gmail.com
