### ISSUE TITLE
Do not delete CompReport.sso

### ISSUE THREAD

**Issue by ElizabethCouncill** [ss3sim/ss3sim#215]
I think the utility of the package is limited by having no option to access expected values or residuals or expected sample sizes, or likelihood contributions for the composition data, which is usually available in CompReport.sso file. Ss3sim deletes this file in the output folder currently.

**Comment by kellijohnson** [comment]
@seananderson should we revert back or make a switch where users can delete them if they want but they are available by default. Not having the reports makes some of the r4ss plots not work among other things. The changes were made here 3c9e808450f1b7d68424cd2d7fd4106c88c73cb1. I am leaning more towards a switch so that users can delete them if they so wish. I know @ElizabethCouncill needs them immediately (as in yesterday).

**Comment by seananderson** [comment]
Thanks for making the quick fix, @kellijohnson . I added an argument `keep_compreport` to `ss3sim_base`, which is `TRUE` by default and merged your branch into master: https://github.com/ss3sim/ss3sim/commit/39cbd8ead070306e41147f5d9b3fd7b5c84f1a53

As with all other arguments, this can be passed through from `run_ss3sim` in the `...`
