### ISSUE TITLE
Add additional clarification to "making models" vignette

### ISSUE THREAD

**Issue by cstawitz** [ss3sim/ss3sim#233]
Working on adapting the petrale sole model for ss3sim, I noticed a few things I had to change in the OM control file that were not documented in the vignette, as well as some additional guidance that would be nice to have.

Not documented:
### Control file
1. Comment out line `#_env/block/dev_adjust_method` for selectivity parameters
2. Set `#_Variance_adjustments_to_input_values` to `0`. Comment out any lines underneath referring to variance adjustments.
3. Set `# number of changes to make to default Lambdas` to `0`. Comment out any lines with default lambda changes below.

Nice to have:
1. In the .dat file, the comment referring to mean body weight does not have a keyword users can search on to find the right line, should add `#_N_meanbodywt`
2. Lines 140-151 ("Testing the new operating model" section) should include code for how to run a single iteration, otherwise the reader has to switch back and forth between vignettes to figure out how to run a single iteration. Additionally, it's unclear which case files are required when you're simply trying to test the model structure and not run a bunch of scenarios - should detail which case files are necessary to run a single test iteration and provide some code for each one under the base case. 
3. Why is the "Testing the new operating model" section before the "Estimation model" section? Don't you need to make an EM to run a single iteration anyway?

**Comment by colemonnahan** [comment]
Hi @cstawitz, 

Your points are valid, and for me really just point to the fact that someone should start with ss3sim OM/EM and adapt them from there. We can't predict what settings will be turned on in control files, so it's hard to document. The ones we have written down are simply the changes we had to make to the models we started with. 

1. Can you provide an example? If you're suggesting adding a comment line to our models then I don't think that's a good idea. We require using the .ss_new files and thus are restricted to what SS3 does. Or am I misunderstanding?
2. I don't know which line numbers you're referring to, but I'm looking at 1.4 of [the html vignette](https://cran.r-project.org/web/packages/ss3sim/vignettes/making-models.html#control-file-modifications). In this case we mean to open a command window and run a single iteration that way, i.e. with flags `-nohess -maxfn 1`. From what I remember ss3sim won't work unless you have an EM setup too, so you can't actually run a simple simulation. In section 2.4 we link to another section showing how to run a simple deterministic simulation that would be useful for testing any new models.
3. We typically make the OM and then adapt it into the EM, so that's the order we used in the vignette. Correct that you need both to run a simulation. Part of the confusion is that here "iteration" means an ADMB function evaulation. We reserve "replicate" for a single run of a simulation (OM and EM). We tried to be consistent with that throughout, so let us know of any mistakes.

**Comment by cstawitz** [comment]
Fixed with latest commit

**Comment by colemonnahan** [comment]
Thanks @cstawitz , it's always good to have fresh eyes on our documentation and trying these things out. Making edits directly is a big bonus.

**Comment by taylori** [comment]
The changes to the documentation look good to me but I'm confused about one
change, the instruction to "Comment out second line entitled
`#_env/block/dev_adjust_method` underneath the section which specifies
selectivity parameters."

It looks like the change_tv function (see
https://github.com/ss3sim/ss3sim/blob/master/R/change_tv.r#L240
<https://github.com/ss3sim/ss3sim/blob/master/R/change_tv.r#L240>), separately
searches for both the first and second occurrences of that string, splits
the line at the "#", converts the value prior to the hash to numeric, and
warns you if the have value of 2 instead of 1. If the conversion to numeric
results in NA, then it replaces the line with "1
#_env/block/dev_adjust_method". Commenting out the line likely leads to
that replacement step occurring but I think it would be preferable to fix
whatever issue was going on that inspired that suggestion in the first
place. Or maybe I'm confused about what's going on.

**Comment by cstawitz** [comment]
Thanks Ian - I'm not sure either.

I commented it out because it was causing an error when running the OM I created. In the echoinput.sso file I am seeing:  "No selparm adjustments, so don't read selparm_adjust_method" when it gets to that line. Maybe the vignette should just say comment out IF there are no selectivity parameter adjustments then? It seems like if you are running `change_tv()` to make the selectivity parameters time-varying in one case but the base OM does not have tv selectivity parameters it should add that line back in..but if the OM does not have adjustments to the selectivity parameters SS will not run. I'd appreciate anyone else's insights!

**Comment by colemonnahan** [comment]
That sounds reasonable Christine. For any discussion on `change_tv` we really need to have @kellijohnson  looped in.

Pinging Kelli

**Comment by kellijohnson** [comment]
It is on my todo list to look at this issue, but I am booked up until 
Thursday probably though I will try to look tomorrow morning.

**Comment by taylori** [comment]
@cstawitz, I see that you are right that the dev_adjust_method line should not be present if there are no time-varying selectivity parameters. But in the control.ss_new files that I looked at for such models, it was already commented out.  Perhaps the problem comes from taking a model with time-varying selectivity present but running a scenario without it. Given that the instructions as they stand, should work in general, it's probably fine to leave them as they are.

**Comment by cstawitz** [comment]
By "as they stand" you mean after my change? I can clarify that it may already be commented out, depending on what model you start at. Also just realized this applies to the EM as well.

**Comment by taylori** [comment]
Yes, I meant after your recent commits, but perhaps a clarification could
still be useful, as well as perhaps adding the motivation behind the
instruction: that the OM and EM files should have time-varying selectivity
turned off and therefore that line should be commented out because the
function to add time-varying selectivity will automatically add it back.

**Comment by cstawitz** [comment]
Done - thanks Ian and Cole for the discussion!
