### ISSUE TITLE
path with `get_bin`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#241]
Searching for the executable within the path may not be the best option for people that have multiple versions of ss3 in their path and for future testing of differences between SS versions. It was suggested to allow users to specify the path to the version of SS3 that they want to use. Need to look into this further, as it was also noted that Linux users may face different obstacles than Windows and Mac users.

**Comment by seananderson** [comment]
Setting up the path on Linux and macOS should be the same. At least I can't think of any differences besides some of the default paths being different. 

Right now it searches for `ss3_24o_opt` or `ss3_24o_safe` so there shouldn't be a problem with having other versions of SS3 installed because they would have a different filename, right?

It would be useful to pass the binary path for testing different versions of SS, but I think we can pass that hurdle once/if we update the code to work with newer versions of SS. But if you feel inspired then go for it!

**Comment by kellijohnson-NOAA** [comment]
Users can easily find which executable is being used via `ss3sim::get_bin()`. For users that want to use a different executable, the executable found using the previous function can easily be replaced with any SS executable knowing that ss3sim functionality might be compromised. This is now explained in more detail [here](9c14ecf).
