### ISSUE TITLE
r4ss version

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#244]
`ss3sim` is dependent on earlier versions of `r4ss` because many updates have been made to the latter to accommodate the newest version of Stock Synthesis. Need to note this in the vignette or on the readme.

**Comment by seananderson** [comment]
I presume this is only a problem for people with the latest GitHub versions of r4ss installed. We could require a specific range of r4ss versions in the description file, but that would overwrite the user’s more recent version, which could be confusing. Perhaps in the meantime we should check the version of r4ss and provide a useful warning on package load if the r4ss version is too high with .onAttach — likely with instructions to install the CRAN version of r4ss. Longterm I guess we have some work ahead of us.

See the section “When you do need side effects” at http://r-pkgs.had.co.nz/r.html#r-differences

**Comment by taylori** [comment]
A warning is surely easier than modifying either package, but the goal with recent changes to r4ss has been to maintain compatibility with earlier versions of SS (still works at least back to SS 3.24f from 2012). However, I'm not surprised that changes in headers (discussed under https://github.com/r4ss/r4ss/issues/141) break things for ss3sim.

I've been slow to update the version on CRAN but it doesn't work with recent versions of SS so it's overdue to be updated, which would create a stronger need for changes to get the two packages working together again.

**Comment by k-doering-NOAA** [comment]
If anyone needs to use the master branch of ss3sim at the time of this writing (version that uses SS 3.24; last commit 5b64ec3270475036dfda4254c280c053bcd5dfad), installing this version of r4ss from github worked for me (thanks to @kellijohnson-NOAA who figured out how far to roll back):
```
library(devtools)
install_github("r4ss/r4ss@2622cfe")
```
If you want to keep the current r4ss version on your computer (i.e., in your default R package library), you can try using [Packrat](https://rstudio.github.io/packrat/) or possibly the replacement for Packrat, [Renv](https://rstudio.github.io/renv/articles/renv.html). I've only used Packrat, but it allows you to create a repository with its own library so that you can use different package versions than those in your main R package library.

Also, please post if this r4ss commit doesn't work for you! Admittedly it has been a few months since I last tried it.

**Comment by kellijohnson-NOAA** [comment]
The development and master branch have been updated to use the most recent version of SS and r4ss, thus is no longer and issue and the developers of ss3sim do not recommend using SS 3.24 given that SS 3.3 is more robust.
