### ISSUE TITLE
find a new name for cod

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#247]
change cod model to have a more generic name
- [x] make a new branch called update3.3
- [x] make this model 3.30 (progress: replaced 3.24 model in branch update_cod)
- [x] check that the model matches the settings for the [cod model](https://github.com/ss3sim/ss3models/tree/master/inst/models/cod) in [ss3sim/ss3models](https://github.com/ss3sim/ss3models)
- [x] remove the cod 3.24

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA does it still make sense to rename cod? I'm not sure, because the original model IS based off of cod, and I don't necessarily think that fact should be obscured. Perhaps the users should decide on their own if "cod" will represent their species' life history well enough? (or if they can make small modifications so that it is representative?) I am not sure I could confidently say that this model is good enough for all gadids, for example, or for moderately-lived species that reproduce more than once in their lifetime on an annual basis...  thoughts?

As for  "add 3.30 cod model to SS model group that undergoes testing with new development and try to implement some way to automate code changes to the model files in ss3sim being copied over to the copy in the SS testmodels folder", I agree that is a long term goal for SS that has not been done (hoping to make some progress in the next few months).

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA I removed both of those tasks and will be closing this issue. When you start working on testing or if we develop functions to change "cod" to another life-history then we will revisit the subject.
