### ISSUE TITLE
duplicated functionality in sampling composition data

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#253]
```sample_lcomp``` and ```sample_agecomp``` are in large duplicates of each other. I think it would be better to have a ```sample_comp``` that is called by the former functions, i.e.,
```
sample_comp <- function(data, ninitcols) {
# generalize old code
}
sample_lcomp <- function() {
data <- dat$lcomp
ninitcols <- 6
sample_comp(data, ninitcols)
...
}
sample_lcomp <- function() {
data <- dat$agecomp
# pull out conditional data
ninitcols <- 9
sample_comp(data, ninitcols)
# merge conditional data back in
...
}
```

**Comment by k-doering-NOAA** [comment]
Sounds like a good idea. I wonder if it would make sense to plan to deprecate `sample_lcomp` and `sample_agecomp`? Or deprecate immediately? I doubt they have many users independently of 
`run_ss3sim()` , and because this code isn't back compatible with 3.24 anyway, it seems like it might be okay to do away with extraneous functions. But perhaps I am wrong about this.

**Comment by k-doering-NOAA** [comment]
Also, as I look at the functions now to write tests (#255), it seems like it could be rewritten to run more efficiently (at least, that is my intuition that may be wrong), because there is lots of subsetting and reassigning and for loops. Seems like it would be possible to vectorize a lot of this code, so perhaps something to consider when trying to speed up ss3sim and I think it may have the other benefit of being less lines of code.

**Comment by seananderson** [comment]
Clarity of code is a good reason to refactor, but regarding efficiency, I'd check with something like the profvis package before refactoring for speed. Hadley has a nice write up here: https://adv-r.hadley.nz/perf-measure.html

**Comment by k-doering-NOAA** [comment]
Thanks @seananderson, that is a great point. We will definitely do some profiling before deciding what (if anything)  should be refactored for efficiency.
