### ISSUE TITLE
check standardize_bounds function

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#263]
This function is not used by other ss3sim functions, so it is not high priority. However, it should be checked that it is performing correctly if it remains with the ss3sim package and modified if not.

**Comment by kellijohnson-NOAA** [comment]
The function probably doesn't work because I remember running into issues with it when we tried to standardize the bounds for the first round of simulations. The theory behind it was, that we didn't want the bounds to be dictating the results but we wanted the bounds to be guided by rational thinking. It was hard to implement a function that allowed for both goals and worked across a variety of models. 

The ultimate __lofty__ goals are ... (feel free to edit this comment and add items to this list)
- [ ] fix standardize_bounds to work with SS 3.3
- [ ] implement an additional logical argument in run_ss3sim that allows for users to choose if their  EM is standardized or write a protocol in a vignette on how users can standardize the bounds and implement that new EM as a different 'species'
- [ ] run some tests to see where the standardization should be changed, i.e., standardizing the bounds to a limit of y for parameter x leads to changes in the model results
- [ ] write up some guidelines on bounds

**Comment by k-doering-NOAA** [comment]
Thanks for the background and it makes sense that this is a hard problem to solve! I think the lofty goals are good if we want to get this function to work properly, but I think it can remain as is for now.

**Comment by kellijohnson-NOAA** [comment]
I am closing this issue for now with the removal of `standardize_bounds` from {ss3sim} in an effort to clean up unused functions within the package and focus on providing great code for necessary actions. Users can set bounds in the EM without needing this function and as @k-doering-NOAA mentioned it is not currently used within the package. I hope future development can find a solution for this but closing for now.
