### ISSUE TITLE
deprecate case files

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#288]
It has been a while since we started using the simdf approach and it appears to be working so case files will be deprecated. @k-doering-NOAA will complete this. 

!missing(om_dir) stop("'om_dir' is deprecated and should be a column in simdf")

**Comment by k-doering-NOAA** [comment]
I started working on this using the [lifecycle pkg](https://github.com/r-lib/lifecycle) functions. @kellijohnson-NOAA , when you get a chance, could you take a look at the changes in the `rm_casefiles` branch and let me know if you think the approach makes sense or not? I found the lifecycle functions pretty easy to use, although I couldn't figure out how to make the changes in 150bae7 less repetative (it seems like it would be possible to use a for loop or apply fxn, but I couldn't figure out how to do it because of the need to tell R when to evaluate expressions or not...)

**Comment by kellijohnson-NOAA** [comment]
# AMAZING

big thanks to @k-doering-NOAA for all of your work on this!
