### ISSUE TITLE
Error in `ss3sim_base` - `Error: Error in if (nver < 3) { : argument is of length zero`

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [ss3sim/ss3sim#367]
Hi,

Please see the command check on the pull request for the `noest` branch to see what is happening

On line 266-267 of `ss3sim_base` the `version` argument is being set to `NULL`
```
    # Find number of years in OM to change recdevs and F
    datfile.orig <- r4ss::SS_readdat(file.path(sc, i, "om", "ss3.dat"),
      version = NULL, verbose = FALSE
```

but then `SS_readdat` throws an error that `nver` argument has length zero.. is there a reason why the version number is set to NULL here?

**Comment by k-doering-NOAA** [comment]
Hi @ChristineStawitz-NOAA , I'm guessing this is due to some work that @kellijohnson-NOAA just did in r4ss (see https://github.com/r4ss/r4ss/pull/643). I think version = NULL could be safely removed from the SS_readdat call (and could be removed elsewhere in the pkg)

**Comment by kellijohnson-NOAA** [comment]
Thanks @ChristineStawitz-NOAA for reporting. I have been working on updating to the latest version of {r4ss} and Stock Synthesis here on the [SS3.30.19 branch](https://github.com/ss3sim/ss3sim/tree/SS3.30.19). Which version of SS3 are you using? I am just trying to think about order of operations and how to best proceed so that you get the changes that you need without additional complications.

**Comment by ChristineStawitz-NOAA** [comment]
Thanks @k-doering-NOAA and @kellijohnson-NOAA - we are using a petrale-based OM run in version 3.30.16. I confirmed that if I remove `version=NULL` both on lines 266 and 505 of `ss3sim_base` it works for our case and updated the `noest` branch with that change

**Comment by kellijohnson-NOAA** [comment]
Closing with the update to use SS3.30.19.1 and the inclusion of #373
