### ISSUE TITLE
New Feature Needed to Sample Index

### ISSUE THREAD

**Issue by chamberlindw** [ss3sim/ss3sim#392]
https://github.com/ss3sim/ss3sim/blob/08552b93d0496d65da5585e28209ba857d5fb4ef/R/sample_index.r#L190

I have an index fleet with normally distributed error and ss3sim samples only lognormal. When I ran some scenarios with the index errtype as normal it resulted in my expected index values that were passed to the EM being effectively 0 across all years. I am going to try running my production model with the index data transformed into log space and a lognormal error type to see if I get similar outputs. If that works I will then run my ss3sim scenarios again with all the indices errtype set to lognormal.

It might be helpful to have ss3sim throw an error if any of the indices error type are not set to lognormal.

**Comment by kellijohnson-NOAA** [comment]
Thank you @chamberlindw for this idea. I couldn't use `dplyr::case_when()` because it ended up changing the original results but `ifelse()` worked to accommodate one additional distribution. Feel free to comment on this closed issue if the values that you end up getting for fleet 4 do not make sense still.
