### ISSUE TITLE
Strange report.sso behaviour 

### ISSUE THREAD

**Issue by kinmic** [ss3sim/ss3sim#416]
Occasional simulation iterations cannot be read by get_results_all() due to a gap in the age length key in the report file (See attached file line 3987). This seems to only affect certain iterations and causes an error in the get_results_all() function. The iteration has a positive determinant hessian, however the final gradient is quite high (0.012) so the issue may be related to convergence. Manually editing the line and removing whitespace allow the file to be read.

SS3 version: 3.30.19.01
r4ss version: 1.49.1
ss3sim version: 1.20.1

[Report_SS0.txt](https://github.com/ss3sim/ss3sim/files/14173665/Report_SS0.txt)

**Comment by kellijohnson-NOAA** [comment]
Sorry that I missed this issue and that I am just responding now. I am guessing that this is fixed in the newest version of Stock Synthesis. I am working on updating the version used inside of ss3sim but in the mean time feel free to update your version locally. To do this, find where ss3sim is located `.Library`, navigate the the previous directory and find ss3sim/bin and replace the exe in the appropriate folder for your operating system. Then, ensure that you are using the latest version of `r4ss`. Please let me know if this fixes the problems that you are having. And, again, I am so sorry that I am just responding now.

**Comment by kinmic** [comment]
No problem, for some reason the error disappeared when I changed the location I was saving simulations to.

**Comment by kinmic** [comment]
No problem, for some reason the error disappeared when I changed the location I was saving simulations to.
